<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<Folder Include="Configuration\" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="ABCpdfCore" Version="11.3.9" />
		<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.1" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\WeatherReportGenerator.Application\WeatherReportGenerator.Application.csproj" />
	</ItemGroup>
</Project>